name: Close preview
on:
  pull_request_target:
    types: [closed]

concurrency:
  group: preview

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: echo Closing preview for PR ${{ github.event.pull_request.number }}
