name: Close preview
on:
  workflow_dispatch:
    inputs:
      pr:
        required: true
        type: string
        description: PR number
  pull_request_target:
    types: [closed]

concurrency:
  group: preview

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - run: echo Closing preview for PR ${{ inputs.pr || github.event.pull_request.number }}
