name: Deploy preview

on:
  workflow_dispatch:
    inputs:
      pr:
        required: true
        type: string
        description: PR number
  workflow_run:
    workflows: [ci]
    types: [completed]
  pull_request_target:
    types: [labeled]

concurrency:
  group: preview

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'pull_request_target' && github.event.label.name == 'deploy-preview') }}
    runs-on: ubuntu-latest

    steps:
      - name: Get PR number
        id: pr-number
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            let prNumber;
            console.log(context);
            switch (context.eventName) {
              case "workflow_dispatch":
                prNumber = context.event.inputs.pr;
                break;
              case "workflow_run":
                prNumber = context.event.workflow_run.pull_requests[0]?.number;
                if (!prNumber) {
                  // PRs sent from forks do not get the pull_requests field set.
                  // https://github.com/orgs/community/discussions/25220
                  prNumber = (await github.rest.pulls.list({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    head: context.event.workflow_run.head_sha,
                  })).data[0].number;
                }
                break;
              case "pull_request_target":
                prNumber = context.event.pull_request.number;
                break;
              default:
                throw new Error(`Unexpected event: ${context.eventName}`);
            }

            if (!prNumber) {
              throw new Error("Could not determine PR number");
            }

            return prNumber;

      - name: Get latest run ID for CI workflow
        id: run-id
        uses: actions/github-script@v7
        env:
          TARGET_PR_NUMBER: ${{ steps.pr-number.outputs.result }}
        with:
          result-encoding: string
          script: |
            const TARGET_PR_NUMBER = +process.env.TARGET_PR_NUMBER;

            let workflowRun;
            try {
                if (context.eventName === "workflow_run") {
                workflowRun = context.event.workflow_run;
              } else {
                let pr;
                if (context.eventName === "pull_request_target") {
                  pr = context.event.pull_request;
                } else {
                  pr = (await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: TARGET_PR_NUMBER,
                  })).data;
                }

                workflowRun = (await github.rest.actions.listWorkflowRuns({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: "ci.yml",
                  head_sha: pr.head.sha,
                })).data.workflow_runs[0];
              }
            } catch (e) {
              console.log(e);
            }

            if (!workflowRun) {
              console.log(`Could not find workflow run for PR ${TARGET_PR_NUMBER}`);
              return;
            }

            if (workflowRun.conclusion !== "success") {
              console.log(`Found ${workflowRun.html_url}, but it did not succeed`);
              return;
            }

            console.log(`Found ${workflowRun.html_url}`);
            return workflowRun.id;

      - name: Download site build from PR
        if: ${{ steps.pr-number.outputs.result }}
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.pr-number.outputs.result }}

      - name: Deploy
        id: deploy
        if: ${{ steps.pr-number.outputs.result }}
        run: |
          echo deploying site
          ls -R site
          echo azure_static_web_apps_api_token=$azure_static_web_apps_api_token
          echo repo_token=$repo_token
          echo action=$action
          echo app_location=$app_location
          echo skip_app_build=$skip_app_build
          echo production_branch=$production_branch
          echo deployment_environment=$deployment_environment
        env:
          azure_static_web_apps_api_token: AZURE_STATIC_WEB_APPS_API_TOKEN_PROD
          repo_token: GITHUB_TOKEN
          action: 'upload'
          app_location: 'site'
          skip_app_build: true
          production_branch: v2
          deployment_environment: ${{ steps.pr-number.outputs.result }}
